source 'https://rubygems.org'

gem 'rails', '3.2.16'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'bootstrap-sass', '~> 3.1.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'devise'
gem 'cancan'
gem 'activeadmin'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'activerecord-sqlserver-adapter'
gem 'tiny_tds'
gem 'unicorn'
gem 'paper_trail', '~> 3.0.0'
group :development do
  gem 'debugger'
  gem 'mysql2'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'lol_dba'
  gem 'irbtools'
  gem 'irbtools-more'
  gem 'terminal-notifier'
  gem 'rails_layout'
end
