mysql: &mysql
  username: rails
  host: localhost
  database: cpm_admin_dev
  username: rails
  adapter: mysql2

sqlserver: &sqlserver
  host: 54.200.112.112
  database: web_db_ruby
  username: rails
  password: India1984!
  adapter: sqlserver



development:
  <<: *mysql
  #<<: *sqlserver
test:
  <<: *mysql

